# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    working_directory: ~/repo/stack
    docker:
      - image: circleci/node:11.9.0-stretch
    steps:
      - checkout:
          path: ~/repo

      # Download and cache dependencies
      - restore_cache:
          key: node_modules-{{ checksum "~/repo/stack/package-lock.json" }}

      - run: npm i

      - save_cache:
          key: node_modules-{{ checksum "~/repo/stack/package-lock.json" }}
          paths:
            - ~/repo/stack/node_modules

      - run: npm run build

      - run:
          environment: 
            CLIENT_REPO: ~/repo/client
          command: npm run cdk deploy
